{
 "title": "clip as a service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "life cycle of a request",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_sum / jina_receiving_request_seconds_count",
     "legendFormat": "receiving-{{job}}"
    },
    {
     "expr": "jina_sending_request_seconds_sum / jina_sending_request_seconds_count",
     "legendFormat": "sending-{{job}}"
    },
    {
     "expr": "text_preproc_second_sum/text_preproc_second_count",
     "legendFormat": "preproc text"
    },
    {
     "expr": "encode_second_sum/encode_second_count",
     "legendFormat": "encode"
    },
    {
     "expr": "jina_process_request_seconds_sum / jina_process_request_seconds_count",
     "legendFormat": "processing-{{method}}"
    }
   ]
  },
  {
   "title": "time to process request",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_sum / jina_receiving_request_seconds_count",
     "legendFormat": "receiving-{{job}}"
    },
    { "expression": "$A -$B", "type": "math" }
   ]
  },
  {
   "title": "text preprocessing time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "text_preproc_second_sum/text_preproc_second_count"
    }
   ]
  },
  {
   "title": "time to process request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "request_processing_seconds_sum / request_processing_seconds_count"
    },
    {
     "expr": "text_preproc_second_sum/text_preproc_second_count",
     "legendFormat": "text-preproc"
    },
    {
     "expr": "encode_second_sum/encode_second_count",
     "legendFormat": "encode"
    }
   ]
  },
  {
   "title": "Number of request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "request_processing_seconds_count"
    }
   ]
  }
 ]
}