{
 "title": "Flow monitoring",
 "time": { "from": "now-10m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Endpoint",
    "query": {
     "query": "label_values(executor_endpoint)\n"
    }
   },
   { "name": "Executor", "query": { "query": "label_values(runtime_name)\n" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "jina_receiving_request_seconds[5m](p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jina_receiving_request_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{runtime_name}}"
    }
   ]
  },
  {
   "title": "Number of Request processed ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_count{runtime_name=~\"gateway.*\"}"
    }
   ]
  },
  {
   "title": "$Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Executor",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Documents processed per endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jina_document_processed", "legendFormat": "{{executor_endpoint}}" }
     ]
    },
    {
     "title": "Number of requests per endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jina_process_request_seconds_count",
       "legendFormat": "{{executor_endpoint}}"
      }
     ]
    },
    {
     "title": "Time spend calling the Executor method link the to endpoint",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jina_process_request_seconds_sum{runtime_name=\"$Executor\"} / jina_process_request_seconds_count{runtime_name=\"$Executor\"}",
       "legendFormat": "{{executor_endpoint}}-process"
      }
     ]
    },
    {
     "title": "Time spend calling between receiving and responding ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jina_receiving_request_seconds_sum{runtime_name=\"$Executor\"} / jina_receiving_request_seconds_count{runtime_name=\"$Executor\"}",
       "legendFormat": "{{executor_endpoint}}"
      }
     ]
    }
   ]
  }
 ]
}