{
 "title": "Flow monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Endpoint",
    "query": {
     "query": "label_values(jina_document_processed_created,endpoint)\n"
    }
   },
   {
    "name": "Executor",
    "query": {
     "query": "label_values(jina_document_processed_created,pod_name)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "jina_receiving_request_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_sum / jina_receiving_request_seconds_count"
    }
   ]
  },
  {
   "title": "Number of Request processed ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_count{pod_name=\"gateway/rep-0/GRPCGatewayRuntime\"}"
    }
   ]
  },
  {
   "title": "$Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Executor",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Documents processed per endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jina_document_processed_total{pod_name=\"$Executor\"}",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Number of requests per endpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jina_process_request_seconds_count{pod_name=\"$Executor\"}",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Time spend calling the Executor method link the to endpoint",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jina_process_request_seconds_sum{pod_name=\"$Executor\"} / jina_process_request_seconds_count{pod_name=\"$Executor\"}",
       "legendFormat": "{{endpoint}}-process"
      }
     ]
    },
    {
     "title": "Time spend calling between receiving and responding ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jina_receiving_request_seconds_sum{pod_name=\"$Executor\"} / jina_receiving_request_seconds_count{pod_name=\"$Executor\"}",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  }
 ]
}